#include <atomic>
#include <chrono>
#include <random>
#include <vector>
#include <fstream>
#include "cereal/archives/portable_binary.hpp"
#include "kul/cpu.hpp"
#include "statick/array.hpp"
#include "statick/linear_model/model_logreg.hpp"
#include "statick/prox/prox_l2sq.hpp"
