name: Statick on ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    KUL_GIT_CO: --depth 10 # is added to git clone calls

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        export PATH="$PWD:$PATH"
        python3 -m pip install pip --upgrade
        python3 -m pip install -r res/pip_deps.txt --user --upgrade
        XTRA="-tx $PWD/res/ci/travis-linux.yaml" KLOG=4 ./test.sh
