name: Statick on ubuntu-latest

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    KUL_GIT_CO: --depth 10 # is added to git clone calls
    MKN_LIB_LINK_LIB: 1
    MKN_PYTHON_LIB_EMBED: 1

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.11', '3.12']
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        export PATH="$PWD:$PATH"
        python3 -m pip install pip -U
        python3 -m pip install wheel -U
        python3 -m pip install -r res/pip_deps.txt -U
        XTRA="-tx $PWD/res/mkn/linux" KLOG=4 ./sh/build_tick.sh
        XTRA="-tx $PWD/res/mkn/linux" KLOG=4 ./sh/test.sh
